[package]
name = "analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full", "visit", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
walkdir = "2.3.2"
rayon = "*"
rand = "*"
prettyplease = "0.2.20"
chrono = "0.4"